### ISSUE TITLE
Why can inventory quantity go negative?

### ISSUE THREAD

**Issue by zczcs12** [zczcs12/CKB#11]
e.g.  [this book](https://ckb.salesbinder.com/v2/items/view/5d1657c5-1280-4f41-b31e-61ea3f71d8bf)

**Comment by slinnecar** [comment]
its a system fault.  I guess it allows for stock that can be reordered so it can temporarily go into minus as it nows its coming in again.  Brodie had promised to fix it but its been on the fix list for 18m !!!

**Comment by zczcs12** [comment]
I added in means of quickly checking for negative quantities so hopefully that should keep things in line easily.
