### ISSUE TITLE
StockList generation ordering

### ISSUE THREAD

**Issue by zczcs12** [zczcs12/CKB#16]
non null clearance items at bottom
Order by Rating descending so that very desirable stock is first

**Comment by slinnecar** [comment]
Looks like you have added 'Rating' as a custom field - thanks.

I think we should have 4 ratings to keep it as simple as possible

1 - the top 25 lines that you see when a client initially opens a stock sheet i.e. the real gems that make you want to read on
2 - the batch of lines underneath '1' that are decent but not amazing
3 - the balance of lines excluding '4' (clearance) below
4 - clearance lines i.e. those with the value 'Yes' beside the Custom Field 'Rating'

I can add the Ratings in if you tell me where to do it

**Comment by zczcs12** [comment]
Yes - I added in Rating field and have changed code to work against it when generating the stocklist.  I actually did it the other way round (best items having a higher rating than clearance).  Obviously I can change this if it's a problem.

The new code will generate the list with a Rating column, so to update them will just be a case of generating the list file, editing the ratings, and then saving the changes back to salesbinder.

In your 4) - I assume you meant to say those with Clearance = 'yes' rather than Rating = 'yes'
________________________________

**Comment by slinnecar** [comment]
The rating method you have done is fine

OK - I can do this with the general data cleanse - just raised a separate issue on this

Yes on 4)
