### ISSUE TITLE
Updating of Current Data

### ISSUE THREAD

**Issue by slinnecar** [zczcs12/CKB#18]
Do I need to do anything with this yet?  

Most can be found by on Keepa but some fields like 'Full RRP' and 'Case Size' I have to get from the latest stock report as these had to be manually put in as were not in sales binder before

I don't think we need Full RRP and Case Size for all historic records - I think for these records its just as much data from Keepa as possible, in particular the stock type tagging.

**Comment by zczcs12** [comment]
I'll have a think about how this could work.  First thought is to be able to output the list csv with data injected into it from keepa if it's currently missing.  Then you just 'save' that file back to salesbinder and it would update all the fields.

I'll try to do this tonight and then give you an update on Wednesday so you can do the backfill.   That ok?

**Comment by slinnecar** [comment]
Thats perfect - I am happy to back fill the data as a one off purge and then hopefully as long as the data is clean in going in, it wont need to be amended other than when we do a stock take and need to change the stock counts

**Comment by slinnecar** [comment]
first update worked absolutely fine

![image](https://user-images.githubusercontent.com/80513809/112867191-8717e280-90b2-11eb-9ed8-aea7ae979905.png)

**Comment by slinnecar** [comment]
I also had to add in another custom field called 'Sales Restrictions' - I have not added this back into the csv file for update as was not sure if that would affect anything

**Comment by slinnecar** [comment]
I will add in all the data from the current stocklist to the csv file that you can't get from keepa and let you know when that is done.  I think its just adding in the keepa at that stage and then adding in the Sales Restrictions

**Comment by slinnecar** [comment]
slightly odd - I did the bulk update of the same cvs file and updated as above but it only recognised one change when I ran the .bat file?

![image](https://user-images.githubusercontent.com/80513809/112873207-3fe12000-90b9-11eb-8f6f-10b2ccea6570.png)
