### ISSUE TITLE
Add CKB price to stock list report

### ISSUE THREAD

**Issue by zczcs12** [zczcs12/CKB#2]

**Comment by zczcs12** [comment]
I think this is part of the stock list already?  or I've misunderstood something?

**Comment by slinnecar** [comment]
its not actually showing ... I have run a stocklist to see the output and the below is what we would like to show (it shows from column A going across)

Barcode
Image
Product Description
Product Type
Product Type 2
Product Type 3
Author
Full RRP
Style
Publisher
Clearance
Case Size
VAT Rate
Condition
Qty

**Comment by zczcs12** [comment]
As discussed on the phone, have also added in 'Territory Restrictions' and 'CKB Net Price' .

**Comment by slinnecar** [comment]
great, I am just adding in Territory Restrictions so that outputs
