### ISSUE TITLE
Missing data to go into currentlist.csv from Keepa

### ISSUE THREAD

**Issue by slinnecar** [zczcs12/CKB#24]
STOCK OUTPUT        KEEPA RECORD
ProductType           Categories: Tree
ProductType2         Categories: Sub
ProductType3          NOT REQUIRED SO CAN BE DELETED

Adult/Kids does not seem to be a separate output on Keepa but that can be added along with Case size/Full RRP by warehouse ... unless there is a way to extract out any 'Categories:Tree' which have 'Childrens Books in them'

**Comment by slinnecar** [comment]
I also had to add in another custom field called 'Sales Restrictions' - I have not added this back into the csv file for update as was not sure if that would affect anything

**Comment by zczcs12** [comment]
Just updated code to process and update 'Sales Restrictions' custom field.  Please sync code to pick up change.

**Comment by zczcs12** [comment]
You want the entire Keepa Tree field in the 'Product Type' field.  I was thinking could put slashes between each part, so the string could be "Books / Subjects / Children's Books / Activities / Crafts & Games / Activity Books" for 9781787721067 for example.  Is that's what is wanted?

The 'Sub' field in keepa just looks to be the last node of the 'Category Tree', so that's easy

**Comment by slinnecar** [comment]
> Just updated code to process and update 'Sales Restrictions' custom field. Please sync code to pick up change.

Thanks - I have synced the change.  'Sales Restrictions' also needs to go in the stock output file please

**Comment by slinnecar** [comment]
> You want the entire Keepa Tree field in the 'Product Type' field. I was thinking could put slashes between each part, so the string could be "Books / Subjects / Children's Books / Activities / Crafts & Games / Activity Books" for 9781787721067 for example. Is that's what is wanted?
> 
> The 'Sub' field in keepa just looks to be the last node of the 'Category Tree', so that's easy

Yes, but using the "Books / Subjects / Children's Books / Activities / Crafts & Games / Activity Books" as an example, we only really need to show Children's Books / Activities / Crafts & Games / Activity Books - if that can only be in one column then thats great.  In an ideal would it would be good to have each of the 4 / in a separate column so its easier for someone to search the data and sort by x, y and z

**Comment by zczcs12** [comment]
As dicussed on phone I need to create another batch file to generate the currentstocklist csv file with fields taken from Keepa.  i.e. the work is done I think, but need to show you how to use it.
