### ISSUE TITLE
Stocklist generation

### ISSUE THREAD

**Issue by slinnecar** [zczcs12/CKB#25]
When I run the stock report it comes up with the below before i open

![image](https://user-images.githubusercontent.com/80513809/114223625-f53c8f00-9967-11eb-9546-eda0adef34f2.png)

and then this

![image](https://user-images.githubusercontent.com/80513809/114223893-464c8300-9968-11eb-81e9-c0b868bde579.png)

**Comment by slinnecar** [comment]
all pulls through lovely except 'Clearance' as nothing seemed to get populated on that

**Comment by zczcs12** [comment]
that's fixed

**Comment by slinnecar** [comment]
it still did it on the last test this morning - its no major drama as you just click yes twice and it takes you through ... so happy to close it as an issue as its far from fundamental
