### ISSUE TITLE
Being able to output bespoke data from the standard stocklist

### ISSUE THREAD

**Issue by slinnecar** [zczcs12/CKB#28]
1) Type
2) Adults/Kids
3) Subtype
4) Publisher
5) Territory Restrictions
6) Qty
7) CKB Nett Price

**Comment by slinnecar** [comment]
Hi, Could we please also add minimum pricing as another bespoke option (we currently have maximum)
Thanks

**Comment by zczcs12** [comment]
> Hi, Could we please also add minimum pricing as another bespoke option (we currently have maximum)
> Thanks

done.  sync code to pickup.

**Comment by slinnecar** [comment]
thanks a lot

**Comment by slinnecar** [comment]
Hi Ben,

Could you please check that the ranking is being used when we output the stocklist.  It does not seem to use to the 1 to 4 ranking anymore.

Thanks

**Comment by zczcs12** [comment]
I'm going to move your comment back to the original sorting issue and close this one Ste.
