### ISSUE TITLE
Stock List (Sheet Split) - Headers/ Category adjustment 

### ISSUE THREAD

**Issue by CreativeSales** [zczcs12/CKB#30]
Hi Ben, 

Please can you help with a couple of amends to the work you have done already:-

1.  Is it possible to split the stock list into specified sheets as seen on attachment below.
![Category](https://user-images.githubusercontent.com/81156123/121009227-d00fa580-c78b-11eb-8eaf-af59b6fde324.JPG)
See below where I have listed the category column to match the sheet preference - so use Column D

2. Please can you use the below image as a guide to show exactly what needs to be exported from Sales Binder when we run the Stock report each time.   
![Top Bar 1](https://user-images.githubusercontent.com/81156123/121013683-10bded80-c791-11eb-8a84-e9abf2bfa0a8.JPG)

**Comment by zczcs12** [comment]
So are we changing 2 things here.

1) the output columns required
2) the ability to split on the group?

on 2) you've got a mixture of both categories (Adult - Fiction / Children's / Food & Drink) and tabs with presumably minimum available quantities (500+ units, 1000+ units).  Do I generate then, a) 'All' in first tab, then b) tab per category, and then c) one tab for 500+ and 1000+ hardcoded?

**Comment by zczcs12** [comment]
I just had a go at this.  It's not clear to me exactly how you would want to split into categories - it has to be on a field or field combination of what gets saved in SalesBinder.  If I split on 'ProductType' at the moment, I get these categories currently:

![image](https://user-images.githubusercontent.com/29564090/121435009-1aed1100-c976-11eb-8ab2-168f6be04a99.png)

What I've done will work fine if the salesbinder information is cleaned up, but are you wanting me to switch on ProductType for the individual categories?

**Comment by slinnecar** [comment]
Hi,
If OK with you it might be easier if you come in (when you have time) and sit with Chris so he can explain
I think its a relatively OK change but might be a lot quicker if just explains it to you

Thanks

**Comment by zczcs12** [comment]
Ok Ste. How does Tuesday afternoon sound?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by slinnecar** [comment]
Perfect
Tyvm

**Comment by slinnecar** [comment]
[Categories.xlsx](https://github.com/zczcs12/CKB/files/6695306/Categories.xlsx)

**Comment by CreativeSales** [comment]
![Final Header](https://user-images.githubusercontent.com/81156123/122948733-0b58c980-d373-11eb-92c9-debe2319867c.JPG)

**Comment by CreativeSales** [comment]
Please see final header above and where information needs to be pulled from.

**Comment by zczcs12** [comment]
Chris - I was just looking at the photo I made of your top-level categories.

Two of them don't make sense for the warehouse to set on a book's ProductType/Category.

'1000+ Units' - this is a tab in the stocklist based on an available quantity filter, but to have as a category implies something could move from 'Adult Fiction' to '1000+ Units' if the qty gets high enough.

'Clearance' - we have this as a separate field in the book record and I would filter for the stocklist tab based on that field.  Again, I don't think it makes sense to give the warehouse the option to put this as a top-level ProductType/Category and so prevent it from being something like 'Adult Non Fiction'.

Am I correct?

**Comment by zczcs12** [comment]
Just looking at what you've saved down for inventory - I see you've put your top-level category in the 'KidsOrAdult' field and the sub-category in the 'ProductType' field.  Not a problem, can adapt.

**Comment by CreativeSales** [comment]
No problem, let me know if I can help with anything.

**Comment by zczcs12** [comment]
> Please see final header above and where information needs to be pulled from.

Ultimately I need to generate everything from SalesBinder - if the title needs to be set from keepa, then it first needs to be saved to the salesbinder record.  Same for the publisher.  This is made easier by the 'keepa augment' argument when generating the csv to to update salesbinder.  I may have to adjust what i'm doing there to help out.  I'll try.

**Comment by zczcs12** [comment]
Pretty sure you don't mean to resize images to 120x22.  They are incredibly thing and don't look anything like your screen print:

![image](https://user-images.githubusercontent.com/29564090/123005174-93f45b80-d3ad-11eb-9891-a1f39e263dab.png)

**Comment by slinnecar** [comment]
> Chris - I was just looking at the photo I made of your top-level categories.
> 
> Two of them don't make sense for the warehouse to set on a book's ProductType/Category.
> 
> '1000+ Units' - this is a tab in the stocklist based on an available quantity filter, but to have as a category implies something could move from 'Adult Fiction' to '1000+ Units' if the qty gets high enough.
> 
> 'Clearance' - we have this as a separate field in the book record and I would filter for the stocklist tab based on that field. Again, I don't think it makes sense to give the warehouse the option to put this as a top-level ProductType/Category and so prevent it from being something like 'Adult Non Fiction'.
> 
> Am I correct?

Yes; 1000+ is simply a list of lines with 1000 or more qty whatever category they are from
Clearance - true - its just auto generated based on what is held in sales binder

**Comment by slinnecar** [comment]
> > Please see final header above and where information needs to be pulled from.
> 
> Ultimately I need to generate everything from SalesBinder - if the title needs to be set from keepa, then it first needs to be saved to the salesbinder record. Same for the publisher. This is made easier by the 'keepa augment' argument when generating the csv to to update salesbinder. I may have to adjust what i'm doing there to help out. I'll try.

OK understand - what happens if there is an error on a publisher on data pulled from keepa and we have to overwrite it manually in salesbinder?  Are you able to allow the same functionality as with the images where the system looks at keepa but if it can find what is required/there is an error, it overwrites the data with whatever is in sales binder (rather than eternally looking for data from keepa in a virtuous loop?)

**Comment by slinnecar** [comment]
> Pretty sure you don't mean to resize images to 120x22. They are incredibly thing and don't look anything like your screen print:
> 
> ![image](https://user-images.githubusercontent.com/29564090/123005174-93f45b80-d3ad-11eb-9891-a1f39e263dab.png)

120 square pls

**Comment by zczcs12** [comment]
> > > Please see final header above and where information needs to be pulled from.
> > 
> > 
> > Ultimately I need to generate everything from SalesBinder - if the title needs to be set from keepa, then it first needs to be saved to the salesbinder record. Same for the publisher. This is made easier by the 'keepa augment' argument when generating the csv to to update salesbinder. I may have to adjust what i'm doing there to help out. I'll try.
> 
> OK understand - what happens if there is an error on a publisher on data pulled from keepa and we have to overwrite it manually in salesbinder? Are you able to allow the same functionality as with the images where the system looks at keepa but if it can find what is required/there is an error, it overwrites the data with whatever is in sales binder (rather than eternally looking for data from keepa in a virtuous loop?)

I'm not sure exactly what you're asking here.

As I see it, ultimately you need full control as to what data is saved/retrieved and that is done by updating salesbinder.
When there are missing images, I try to find them and upload them to salesbinder.
When text data about books is wrong, you can generate the list.csv, update it, then re-upload it to salesbinder.
Then when we generate the stocklist, it's based on the data you've vetted and saved.

Salesbinder is then your effective internal record about a book item for sale, though you may be sourcing information to help you from other sources (keepa / abebooks / etc).

Have I missed something?

**Comment by slinnecar** [comment]
no - that is spot on

**Comment by slinnecar** [comment]
have updated github and run the stocklist with no filters
it runs it all and creates a file but wont let me open.  Its 24mg so unsure if size is an issue?

![image](https://user-images.githubusercontent.com/80513809/123942600-348ce180-d993-11eb-933c-cf64cc74f3f4.png)

**Comment by zczcs12** [comment]
I'm not surprised the file size has got a lot bigger - we expanded from 60x60 images to 200x200 images, so 11 times bigger, and they appear minimum 2 times per file now, and up to 4 times.

I don't think it's the size of the file that's the issue.  I use the opensource equivalent 'Libre Calc' which opens the file with no problems.  However, after googling around, I can see this is quite a common problem that Excel doesn't fully support the OpenXml standards that I've implemented in. 

https://www.easeus.com/computer-instruction/the-file-is-corrupted-and-cannot-be-opened.html#1

Can you try the steps on that link, close excel, and then try to open the generated file?  

The hope is
* those steps fix your ability to open the file in Excel
* that Excel manages to sufficiently compress the images to make the file workable (again, I can't test with Excel, and Libre doesn't have a function to compress all images in the same way Excel does).

**Comment by slinnecar** [comment]
Thanks.
We have both tried making the changes but no joy
Maybe we just need to make it as two output spreadsheets and join it back together at this end?

**Comment by slinnecar** [comment]
Could you please try splitting into 2 outputs

1) All stock
2) The balance of tabs

Chris can then patch together and hopefully after reducing the image resolutions, will bring the overall size to below 10mg

tyvm

**Comment by zczcs12** [comment]
Yep will do this evening

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by zczcs12** [comment]
Ok - have done that.  so 2 files will be produced.  The first with the filename that was requested with all items in it, and the second with the same filename appended with "_tabs" that has the balance of the tabs.

**Comment by slinnecar** [comment]
Have updated.

The main stock list outputs fine

The tabbed version is coming up with the same issue i.e. a corrupt file.  Have run all the other checks but still corrupting

**Comment by zczcs12** [comment]
I think I've cracked it.

That last info was helpful - it meant that it was nothing to do with size, but to do with creating a multi-tabbed document.  I don't have Excel to test, but I uploaded the multi-tab one to Google drive and it failed to render it = good, as i have something to get working...

I then found an article that explained a similar problem and how to fix it - have implemented that.  The multi-tab version now renders in google drive (google sheets) so I'm hoping that the same will happen for you.  Please could you resync the code and try?

If this works, then there'll be nothing stopping me just going back to generating one spreadsheet, with the many tabs that you originally requested.  Let me know, B.

**Comment by slinnecar** [comment]
Boom - that is it solved. 

Feel free to join them back up

Thanks a lot

**Comment by zczcs12** [comment]
Changes made to combine stocklist into one spreadsheet.

**Comment by slinnecar** [comment]
works great thanks
